### ISSUE TITLE
Rmarkdown intersect

### ISSUE THREAD

**Issue by BrunoVilela** [wallaceEcoMod/wallace#163] opened 2018-09-19 19:12 UTC
Hi guys,

the download Rmd files are not running correct. Specifically, I have noted the following errors: 

- intersect <- sp::over(occs.xy, selPoly) # This gives an error
I substitute for:
- intersect <- sp::over(SpatialPoints(occs.xy), selPoly) # This works

The code that is used to  predict to the future also gives an error, because the name of the future variables are wrong (should be bio1, bio2.... bioN).

I suggest to knit the Rmd file after working on Wallace, to see if the entire code works.  

Bruno

**Comment by gepinillab** [comment] 2018-09-19 19:30
Hi Bruno,

Just for checking, are you getting this errors in the CRAN v1.0.5/master branch?

I fixed both errors in the upcoming version of Wallace ('maxnet' branch).

Best,
Gonzalo

**Comment by BrunoVilela** [comment] 2018-09-19 20:17
Great! Yes, I was using the master branch. Should I use the 'maxnet', is it the most up to date?

**Comment by BrunoVilela** [comment] 2018-09-19 20:42
Ok, just tried with the maxnet version. Worked fine, although the final plot was not working. It was plot(pred), but pred did not exist (with bioclimática model). I changed and it worked.

**Comment by gepinillab** [comment] 2018-09-19 21:48
Bruno, thanks for your feedback! The issue is now fixed in the *maxnet* branch.

**Closed** 2018-10-09 18:40 UTC
Labels: bug, devFixed
