### ISSUE TITLE
Not able to partition occs

### ISSUE THREAD

**Issue by Pgalante** [wallaceEcoMod/wallace#347] opened 2021-04-12 20:24 UTC
multiSp branch: In Part Occs component, neither module allows for partitioning occurrences. Cannot move past this component.

**Comment by andrepazv** [comment] 2021-04-12 20:40
@Pgalante can you give us more info? It works fine on my end

**Comment by gepinillab** [comment] 2021-04-12 20:51
I was not able to reproduce this issue. Everything is working fine on my machine.
@Pgalante Which ENMeval version do you have installed on your machine?

**Comment by andrepazv** [comment] 2021-04-12 20:57
It was an old ENMeval version closing this one :D

**Closed by andrepazv** 2021-04-12 20:57 UTC
