### ISSUE TITLE
BIOCLIM won't run/Error with ENMeval

### ISSUE THREAD

**Issue by rskearney** [wallaceEcoMod/wallace#350] opened 2021-05-21 14:05 UTC
I am using wallace as part of an assignment for school and came across this issue. I was able to get through most of the application without a hick-up but when I got to tab 6 and tried to run BIOCLIM it failed. The shiny app had a grey semi-transparent overlay and the buttons stopped working (Screenshot 1). In the console of R studio, I got the following error message: 

"Warning: Error in : 'corrected.var' is not an exported object from 'namespace:ENMeval'" (Screenshot 2)

I did a little research and found out that ENMeval had been updated to version 2.0.0 on 5/19/2020 (the same day that I was trying to run wallace). Reviewing the release news indicate that this update includes a "Complete redesign of nearly all functionality." Is it possible that the developers of ENMeval changed how 'corrected.var' functions and this change is throwing of wallace? I am not positive, but this might be why wallace failed to run BIOCLIM. 

I was running wallace in R studio and using R version 4.1.0 x64. I also tried using 4.0.5 and ENMeval version 0.3.1. 

Screenshots:
![5](https://user-images.githubusercontent.com/70336360/119148985-0c68a500-ba1b-11eb-8be0-3bc7d96e8f50.PNG)
Screenshot 1

![screenshot](https://user-images.githubusercontent.com/70336360/119148261-51d8a280-ba1a-11eb-920f-44e997d41d98.PNG)
Screenshot 2

**Comment by gepinillab** [comment] 2021-05-21 17:22
Hi @rskearney,

The new version of ENMeval has some changes that make Wallace break. We already were aware of this problem and submit a fix to CRAN a couple of days ago. Unfortunately, It is taking longer than we expect. In the meantime, you can install Wallace from GitHub; this needs to fix the issue. You can use the following code:

`remotes::install_github("wallaceecomod/wallace")`

Please let us know if this fixes the issue. Also, I will let you know when the new Wallace version is updated on CRAN.

Best,
Gonzalo

**Comment by gepinillab** [comment] 2021-05-24 16:58
Hi @rskearney,

The Wallace version that fixes the problem is on CRAN (https://cran.r-project.org/web/packages/wallace/index.html). Please update Wallace and let us know if this fixes the problem.

Best,
Gonzalo

**Comment by rskearney** [comment] 2021-05-25 17:05
Hi @gepinillab,

Sorry for the delay. I followed your instructions and after installing two additional packages, "ecospat" and "rangeModelMetadata", I was able to run the BIOCLIM model without any issues. See Screenshots for the two errors and the packages that I needed to install. Thanks for your help. Let me know if you have any questions.

Screenshots:
![testing_wallace](https://user-images.githubusercontent.com/70336360/119539001-b0bf5400-bd59-11eb-9df7-fb472ed6c8ef.PNG)
![testing_wallace2](https://user-images.githubusercontent.com/70336360/119539003-b157ea80-bd59-11eb-99ec-99b697a29559.PNG)



Best,
Rob

**Comment by gepinillab** [comment] 2021-05-25 17:17
Hi Rob,

Thanks for reporting the issues regarding ecospat and rangeModelMetadata. Both packages are suggested to install on ENMeval. @jamiemkass please take a look at this problem.

I will proceed to close this issue. @rskearney let us know if you have problems in the future.

Best,
Gonzalo

**Closed by gepinillab** 2021-05-25 17:17 UTC
Labels: awaiting reply, bug

**Comment by jamiemkass** [comment] 2021-05-27 05:09
For reference, please download ENMeval 2.0.1 from the Github repo master branch to fix these issues.
